FROM golang:1.24.1-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o chat-server ./cmd/chat-server

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/chat-server .

EXPOSE 8080

CMD ["./chat-server"] 