FROM golang:1.24.1-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o content-moderator ./cmd/content-moderator

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/content-moderator .

CMD ["./content-moderator"] 