FROM golang:1.24.1-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o chat-web ./cmd/chat-web

FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/chat-web .
COPY --from=builder /app/public ./public

EXPOSE 12346

CMD ["./chat-web"] 